# Generated by Django 3.2.8 on 2021-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211028_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='preference',
            field=models.CharField(max_length=30),
        ),
    ]
